apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rag-knowledge-assistant
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        
        # CPU and memory allocation
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        
        # Timeout settings
        run.googleapis.com/timeout: "300s"
        
        # VPC connector for private resources
        run.googleapis.com/vpc-access-connector: rag-vpc-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      serviceAccountName: rag-service-account@YOUR_PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - name: rag-assistant
        image: gcr.io/YOUR_PROJECT_ID/rag-knowledge-assistant:latest
        
        ports:
        - name: http1
          containerPort: 8080
        
        env:
        # Application configuration
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
          
        # Google Cloud configuration
        - name: GOOGLE_CLOUD_PROJECT
          value: "YOUR_PROJECT_ID"
        - name: GCP_REGION
          value: "us-central1"
          
        # Database configuration
        - name: BIGQUERY_DATASET
          value: "rag_analytics"
        - name: FIRESTORE_COLLECTION_PREFIX
          value: "prod_rag"
          
        # LLM configuration
        - name: DEFAULT_MODEL
          value: "gpt-4-turbo-preview"
        - name: MAX_TOKENS
          value: "4096"
        - name: TEMPERATURE
          value: "0.1"
          
        # RAG configuration
        - name: CHUNK_SIZE
          value: "512"
        - name: CHUNK_OVERLAP
          value: "50"
        - name: RETRIEVAL_TOP_K
          value: "10"
        - name: SIMILARITY_THRESHOLD
          value: "0.75"
        
        # Redis configuration
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: redis-url
              
        # API keys from Secret Manager
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: openai-api-key
              
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: jwt-secret-key
        
        # Performance configuration
        - name: API_RATE_LIMIT
          value: "100"
        - name: CACHE_TTL
          value: "3600"
        - name: ENABLE_METRICS
          value: "true"
        
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "2Gi"
        
        # Startup probe
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 5
        
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 5
        
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5

  traffic:
  - percent: 100
    latestRevision: true 